### ISSUE TITLE
No module named 'utils.dnq'

### ISSUE THREAD

**Issue by kanybekasanbekov** [hustzxd/EfficientPyTorch#2]
Hello, I have tried to run your code but I got the following error.
```
Traceback (most recent call last):
  File "examples/classifier_imagenet/main.py", line 1, in <module>
    from examples import *
  File "/home/mobilint/work_kanye/EfficientPyTorch/examples/__init__.py", line 22, in <module>
    from utils.dnq import dnq_scheduler
ModuleNotFoundError: No module named 'utils.dnq'
```
It turns out there is nothing related `dnq` in the `utils` folder, I suppose you did not upload it to GitHub. Can you help me with this?

**Comment by ardywibowo** [comment]
Any update on this?

**Comment by kanybekasanbekov** [comment]
not really :(

**Comment by hustzxd** [comment]
Sorry for that, I have updated the code and changed the interface to protobuf.
